env:
  global:
  - CC_TEST_REPORTER_ID=f6989ec2a44034ba13664d3b8732314f54fb7e07d9fd1cc0ca08e8238fccfd22
language: ruby
rvm:
- 2.3
deploy:
  provider: rubygems
  api_key:
    secure: UC26o6w1LDYftpDLumAZSVgT3XAQhdIz9eoHSQ0zp2l0zIEZr1iHEnWXeX3XgE21mZLBflCT+fqG0iVUzXn1kWczRoNF6LekpJi3WBl11gYEndRxwfgCclQBOYY9wSMZFI1K4AmSxpvmGo1OgNY7CkBgAQSa+NB3R6gkPFyKCvXiH3b7yxrK310zGlPFg1SHSUnd6bAiEu74wRqIAa3eD/R8tVBuobh3I5GXLSUdhhlAEqoUkvsevyM+C0zzxOpa5SVZ/8MarkGwvgWy0XQJAFclxErH4QLkbbajn6Q1XGgQqUltwAL6XLVAKjQeLJdu7gMbjUJ8t+uSgDgifpxDwEs3RHarIE8p4ju7jklbt34ADT+qv6zRS06R1xVyiMZfsVKQmea1fNdGsDeafnqp0TcE7Qu62XoyiC4BsYremWP8SePDKXS3qpQqQr1bpBtmMuzkcD1MnZukv4Cq63k1kXCNA/OdxOfoQUEGuI+GkHt5hZkDT6ltgefR7Ifhb9Ixk4kk0PP/nYpR5l0VAedeIluHMnlxp3mijPiPVSXtLkFuuwt2HBIcTpFK/8vwMsZsMZ+VTcpLuSsW4c9K/bINXtcFn6RO827N/fzNeNez96BHVBMCDUmGJLaZh8BzNn6paZU3O1RoSjDL/VIiLulpVhyJjkx8ZuHDbAQqDytIrZw=
  on:
    tags: true
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
